# Generated by Django 2.0.6 on 2018-06-29 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodotto_Dispensa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantità', models.PositiveSmallIntegerField(help_text='quantità prodotto')),
                ('scadenza', models.DateField(help_text='gg/mm/aa')),
                ('nome', models.CharField(help_text='nome prodotto', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Prodotto_Spesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantità', models.PositiveSmallIntegerField(help_text='quantità prodotto')),
                ('prezzo', models.DecimalField(decimal_places=2, help_text='prezzo prodotto', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('nome', models.CharField(help_text='nome prodotto', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Spesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(help_text='Nome spesa', max_length=32)),
                ('prezzo_tot', models.DecimalField(decimal_places=2, help_text='prezzo spesa', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('prodotto', models.ManyToManyField(to='api.Prodotto_Spesa')),
            ],
        ),
    ]
